# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e069615e97c6b80d668345a7eee8d87239f7b54ad2d7d5cbcd4b086063b76981efe21404b36b3adcf0f2ae967643350baccd8cdf55acb2d06f6e31bcc744577a

test:
  secret_key_base: e382ea0832bfd4c4839bedbae46bd0a2756f729c8153dda01e37bccee10daab44b4384f4f1529d5b0d8ab5c8730574989e01be695064eec71b8fa87e39b4ce43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
